version: '3'

services:
  cache:
    build: .
    ports:
      - 1972:1972
      - 57772:57772
    volumes:
      - ~/cache.key:/usr/cachesys/mgr/cache.key
      - ./src:/opt/advent/src
      - ./input:/opt/advent/input:ro
    