version: '3'

services:
  iris:
    build: .
    ports:
      - 52773:52773
    volumes:
      - ~/irisdocker.key:/usr/irissys/mgr/iris.key
      - ./src:/opt/advent/src
      - ./input:/opt/advent/input
    