version: '3.7'
services:
  iris:
    build:
      context: .
      args:
        - ADVENT_SESSION=${ADVENT_SESSION}
    init: true
    ports:
      - 52773
    volumes:
      - ./src:/opt/advent/src
      - ./input:/opt/advent/input
    