version: '3'

services:
  iris:
    build:
      context: .
      args:
        - ADVENT_SESSION=${ADVENT_SESSION}
    ports:
      - 52773:52773
    volumes:
      - ~/irisdocker.key:/usr/irissys/mgr/iris.key
      - ./src:/opt/advent/src
      - ./input:/opt/advent/input
    