ROUTINE Advent17.Day5
#include helper
Start(part=1) public {
  $$$inputAll(input)
  #; set input = $lb(0,3,0,1,-3)
  set pos=1,step=$lg(input)
  for steps=1:1 {
    #; do draw(input, pos)
    set $li(input, pos) = $lg(input, pos) + $select((part=2)&&($lg(input, pos)>=3): -1, 1: 1)
    set pos=pos+step
    set step=$lg(input, pos)
    quit:step=""
  }
  write !,"steps = ",steps
}
draw(input, pos) {
  set $li(input, pos) = "("_$lg(input, pos)_")"
  write !,$lts(input, "  ")
}